"""
This type stub file was generated by pyright.
"""

import unittest

HTTPS_ENVIRON = ...
def hello_world(): # -> Literal['Hello, world']:
    ...

def with_nonce(): # -> str:
    ...

class TestTalismanExtension(unittest.TestCase):
    def setUp(self): # -> None:
        ...
    
    def testDefaults(self): # -> None:
        ...
    
    def testForceSslOptionOptions(self): # -> None:
        ...
    
    def testHstsOptions(self): # -> None:
        ...
    
    def testFrameOptions(self): # -> None:
        ...
    
    def testContentSecurityPolicyOptions(self): # -> None:
        ...
    
    def testContentSecurityPolicyOptionsReport(self): # -> None:
        ...
    
    def testContentSecurityPolicyNonce(self): # -> None:
        ...
    
    def testDecorator(self): # -> None:
        ...
    
    def testDecoratorForceHttps(self): # -> None:
        ...
    
    def testForceFileSave(self): # -> None:
        ...
    
    def testBadEndpoint(self): # -> None:
        ...
    
    def testFeaturePolicy(self): # -> None:
        ...
    
    def testPermissionsPolicy(self): # -> None:
        ...
    
    def testDocumentPolicy(self): # -> None:
        ...
    


